/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ay27;

import javax.swing.*;
import javax.swing.text.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.List;

/**
 * @author ay27
 */
public class Ui extends javax.swing.JFrame implements UiIntef {

    /**
     * Creates new form Ui
     */

    private Callback handler;
    public DefaultListModel<String> friendListModel;

    public Ui(Callback handler) {
        this.handler = handler;
        friendListModel = new DefaultListModel<>();
        initComponents();
        setVisible(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        friendListView = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        msgEditor = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        msgViewer = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mySelfNameTextField = new javax.swing.JTextField();
        fileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        sendBtn.setText("发送");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        friendListView.setModel(friendListModel);
        friendListView.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        friendListView.setSelectedIndex(0);
        friendListView.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                friendListViewValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(friendListView);

        jLabel1.setText("好友");

        msgEditor.setSize(20, 5);
//        msgEditor.setColumns(20);
//        msgEditor.setRows(5);
        msgEditor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                msgEditorKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(msgEditor);

        msgViewer.setEditable(false);
        msgViewer.setSize(20, 5);
//        msgViewer.setColumns(20);
//        msgViewer.setRows(5);
        jScrollPane4.setViewportView(msgViewer);

        jLabel3.setText("消息");

        jLabel4.setText("编辑（按Ctrl+Enter发送）");

        jLabel2.setText("我：");

        mySelfNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mySelfNameTextFieldKeyReleased(evt);
            }
        });

        fileButton.setText("发送文件");
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane3))
                                                .addComponent(jLabel3)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(fileButton))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(mySelfNameTextField)))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(mySelfNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane4)
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(fileButton))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        handler.onSendBtnAction(this);
    }//GEN-LAST:event_sendBtnActionPerformed

    private void msgEditorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msgEditorKeyReleased
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_ENTER) {
            handler.onSendBtnAction(this);
        }
    }//GEN-LAST:event_msgEditorKeyReleased

    private void friendListViewValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_friendListViewValueChanged
        handler.onFriendSelected(this, evt.getFirstIndex());
    }//GEN-LAST:event_friendListViewValueChanged

    private void mySelfNameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mySelfNameTextFieldKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            handler.onMySelfNameChanged(this.mySelfNameTextField.getText());
        }
    }//GEN-LAST:event_mySelfNameTextFieldKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        handler.onWindowClosing();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        JFileChooser jFileChooser = new JFileChooser("选择需要传从的文件");
        jFileChooser.showOpenDialog(null);

        File file = jFileChooser.getSelectedFile();
        if (file != null) {
            handler.onSendFile(file);
        }
    }//GEN-LAST:event_fileButtonActionPerformed


    @Override
    public void setMsgViewerText(final List<Message> msgs) {
        Document doc = msgViewer.getStyledDocument();
        try {
            doc.remove(0, doc.getLength());
        } catch (BadLocationException e) {
            e.printStackTrace();
        }

        SimpleAttributeSet metas = new SimpleAttributeSet();
        StyleConstants.setForeground(metas, Color.GRAY);
        StyleConstants.setBold(metas, true);
        StyleConstants.setFontSize(metas, 12);

        SimpleAttributeSet msgAttr = new SimpleAttributeSet();
        StyleConstants.setFontSize(msgAttr, 16);

        SimpleDateFormat df = new SimpleDateFormat("MM-dd HH:mm:ss");

        for (Message msg : msgs) {
            try {
                if (msg.isMySelf()) {
                    doc.insertString(doc.getLength(), "我: " + df.format(msg.getDate()), metas);
                } else {
                    doc.insertString(doc.getLength(), msg.getUserName() + ": " + df.format(msg.getDate()), metas);
                }
                doc.insertString(doc.getLength(), "\n" + msg.getContent() + "\n\n", msgAttr);
            } catch (BadLocationException e) {
                e.printStackTrace();
            }
        }
    }

    @Override
    public String getMsgEditorText() {
        return msgEditor.getText();
    }

    @Override
    public void cleanMsgEditor() {
        msgEditor.setText("");
    }

    @Override
    public void setFriendList(String[] friends) {
        friendListModel.removeAllElements();
        for (int i = 0; i < friends.length; i++) {
            friendListModel.add(i, friends[i]);
        }
    }

    @Override
    public int getSelectedUser() {
        return friendListView.getSelectedIndex();
    }

    @Override
    public void selectUser(int index) {
        friendListView.setSelectedIndex(index);
    }

    @Override
    public void setMySelfName(String name) {
        this.mySelfNameTextField.setText(name);
    }

    @Override
    public File recvFile(String userName, String fileName) {
        int accpet = JOptionPane.showConfirmDialog(null, "是否接收来自 " + userName + " 的文件: " + fileName + " ?", "文件接收", JOptionPane.YES_NO_OPTION);
        if (accpet == 1) {
            System.out.println("accept = "+accpet);
            return null;
        }
        JFileChooser jFileChooser = new JFileChooser("选择保存的位置");
        jFileChooser.showSaveDialog(null);
        return jFileChooser.getSelectedFile();
    }


//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Ui(null).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fileButton;
    private javax.swing.JList<String> friendListView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane msgEditor;
    private javax.swing.JTextPane msgViewer;
    private javax.swing.JTextField mySelfNameTextField;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
